server:
  servlet:
    context-path: /
    session:
      timeout: 30m
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://139.196.92.241:3306/usm?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: mf1832225
    driver-class-name: com.mysql.cj.jdbc.Driver